### ISSUE TITLE
Framerate affects simulation speed

### ISSUE THREAD

**Issue by PonasKovas** [Mxple/TPGsim#1]
Hello, love this tool, but for me, especially in the beginning it runs only on like ~40 fps and the whole simulation is very noticeably slower and easier, later it gets up to 60 fps and becomes normal.

Maybe you forget to multiply object translations by the framerate delta?

**Comment by mxple** [comment]
Hi, the simulation does indeed run according to frame rate and not delta time. Frame rate *should* be a fixed 60 fps if your computer is capable of reaching it. I don't think performance is a bottleneck as the simulation is very lightweight. Can you provide PC details including operating system and CPU?

**Comment by PonasKovas** [comment]
I am running it through a virtual machine that's why the performance is not
very good.

**Comment by mxple** [comment]
Unfortunately, I don't have plans to continue maintaining this project in the near future. Feel free to put in a pull request though.
